### ISSUE TITLE
Add a way to retry db connection if failed

### ISSUE THREAD

**Issue by Ponchoalfonso** [prisma/migrate#558]
## Problem
I'm using docker compose to run my application using two containers, one running mariadb, and other running my node app using Prisma. The problem is that according to Docker compose documentation, there is no way to wait until a container is ready, in this case there is no way to tell my node app to wait until mariadb is ready and so Prisma can make the connection with no problem.

According to recommendations and good practices the best way to address this problem is to make your application retry the database connection. I'd like to run migrations when my app container is created, so Prisma needs to keep on trying to connect to the database container before running the migration. Prisma doesn't offer a feature like this and I can't find a workaround for this.

## Suggestions
It would be great to maybe have an option on the migrate command like the following:
``` console
npx prisma migrate up -retry 5 --experimental
```
Where the 5 means the amount of attempts every 2 seconds (or any other time interval).

Another suggestion is to make the PrismaClient try to reconnect if for some reason the connection with the database is lost.

**Comment by Jolg42** [comment]
Hi @Ponchoalfonso 

So would `depends_on` solve your problem in a docker compose file? See [documentation](https://docs.docker.com/compose/startup-order/).

Can be used like this
```yaml
version: '3.7'
services:
  app:
    image: node:10
    volumes:
      - ../../../:/app
    working_dir: /app
    command: /app/run.sh
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    volumes:
      - mysql:/var/lib/mysql

volumes:
  postgres:
  mysql:

```
